/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cmp.github

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App
        assertNotNull(classUnderTest.result, "app should have a greeting")
    }
}
