/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cmp.github

import kotlinx.coroutines.*
import kotlinx.datetime.Clock
import kotlin.system.exitProcess

object App {
    private var _result = Clock.System.now().toString()
    val result: String
        get() {
            return _result
        }

    fun start(userName: String, token: String) {
        runBlocking {
            launch { // launch a new coroutine and keep a reference to its Job
                val displayResult = GitHubRepository().getRepos(userName, token)
                _result = displayResult.displayString
            }
        }
    }
}

fun main(args: Array<String>) {
    var userName = ""
    var token = ""
    if (args == null || args.size < 2 || args[0].isNullOrEmpty() || args[1].isNullOrEmpty()) {
        println("Please enter valid User Name and Token")
        println("java -jar app-all.jar <username> <token>")
        exitProcess(0)
    }

    userName = args[0]
    token = args[1]

    App.start(userName, token)
    println("")
    println("")
    println(App.result)
    exitProcess(0)
}
